// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Api>>
abstract class Api implements RustOpaqueInterface {
  Future<Vote> castVote({
    required String roomId,
    required String voterId,
    required String targetId,
  });

  Future<String> createRoom({
    required String roomName,
    required int maxPlayers,
  });

  Future<String> forceNextPhase();

  Future<String> getGameState();

  Future<List<String>> getLocalIps();

  Future<String> joinRoom({required String hostIp});

  /// Stub: auth is handled by HTTP POST /auth/login
  Future<User> login({required String username, required String password});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new Api instance. The database_url is ignored — DB is managed by the HTTP server.
  static Future<Api> newInstance({required String databaseUrl}) =>
      RustLib.instance.api.crateApiApiNew(databaseUrl: databaseUrl);

  /// Compatibility constructor used by Flutter bridge (database_url ignored — auth is HTTP-only now)
  static Future<Api> newWithDb({required String databaseUrl}) =>
      RustLib.instance.api.crateApiApiNewWithDb(databaseUrl: databaseUrl);

  /// Stub: auth is handled by HTTP POST /auth/register
  Future<User> register({required String username, required String password});

  Future<ChatMessage> sendMessage({
    required String roomId,
    required String userId,
    required String message,
  });

  /// Start the game engine for a specific room
  Future<String> startGame({required String roomId});

  Future<String> submitAction({
    required String actorId,
    required String actionType,
    String? targetId,
  });

  Future<String> testConnection();

  /// Stub: DB is server-side only
  Future<String> testDb();

  /// Stub: profile updates not yet implemented
  Future<void> updateUsername({
    required String userId,
    required String newUsername,
  });
}
