// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 480678061;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'areyoughost_core',
        ioDirectory: '../core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Vote> crateApiApiCastVote({
    required Api that,
    required String roomId,
    required String voterId,
    required String targetId,
  });

  Future<String> crateApiApiCreateRoom({
    required Api that,
    required String roomName,
    required int maxPlayers,
  });

  Future<String> crateApiApiForceNextPhase({required Api that});

  Future<String> crateApiApiGetGameState({required Api that});

  Future<List<String>> crateApiApiGetLocalIps({required Api that});

  Future<String> crateApiApiJoinRoom({
    required Api that,
    required String hostIp,
  });

  Future<User> crateApiApiLogin({
    required Api that,
    required String username,
    required String password,
  });

  Future<Api> crateApiApiNew({required String databaseUrl});

  Future<Api> crateApiApiNewWithDb({required String databaseUrl});

  Future<User> crateApiApiRegister({
    required Api that,
    required String username,
    required String password,
  });

  Future<ChatMessage> crateApiApiSendMessage({
    required Api that,
    required String roomId,
    required String userId,
    required String message,
  });

  Future<String> crateApiApiStartGame({
    required Api that,
    required String roomId,
  });

  Future<String> crateApiApiSubmitAction({
    required Api that,
    required String actorId,
    required String actionType,
    String? targetId,
  });

  Future<String> crateApiApiTestConnection({required Api that});

  Future<String> crateApiApiTestDb({required Api that});

  Future<void> crateApiApiUpdateUsername({
    required Api that,
    required String userId,
    required String newUsername,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Api;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Api;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ApiPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Vote> crateApiApiCastVote({
    required Api that,
    required String roomId,
    required String voterId,
    required String targetId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_String(voterId, serializer);
          sse_encode_String(targetId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vote,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiCastVoteConstMeta,
        argValues: [that, roomId, voterId, targetId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiCastVoteConstMeta => const TaskConstMeta(
    debugName: "Api_cast_vote",
    argNames: ["that", "roomId", "voterId", "targetId"],
  );

  @override
  Future<String> crateApiApiCreateRoom({
    required Api that,
    required String roomName,
    required int maxPlayers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(roomName, serializer);
          sse_encode_i_32(maxPlayers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiCreateRoomConstMeta,
        argValues: [that, roomName, maxPlayers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiCreateRoomConstMeta => const TaskConstMeta(
    debugName: "Api_create_room",
    argNames: ["that", "roomName", "maxPlayers"],
  );

  @override
  Future<String> crateApiApiForceNextPhase({required Api that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiForceNextPhaseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiForceNextPhaseConstMeta => const TaskConstMeta(
    debugName: "Api_force_next_phase",
    argNames: ["that"],
  );

  @override
  Future<String> crateApiApiGetGameState({required Api that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetGameStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetGameStateConstMeta =>
      const TaskConstMeta(debugName: "Api_get_game_state", argNames: ["that"]);

  @override
  Future<List<String>> crateApiApiGetLocalIps({required Api that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetLocalIpsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetLocalIpsConstMeta =>
      const TaskConstMeta(debugName: "Api_get_local_ips", argNames: ["that"]);

  @override
  Future<String> crateApiApiJoinRoom({
    required Api that,
    required String hostIp,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(hostIp, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiJoinRoomConstMeta,
        argValues: [that, hostIp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiJoinRoomConstMeta => const TaskConstMeta(
    debugName: "Api_join_room",
    argNames: ["that", "hostIp"],
  );

  @override
  Future<User> crateApiApiLogin({
    required Api that,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiLoginConstMeta,
        argValues: [that, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiLoginConstMeta => const TaskConstMeta(
    debugName: "Api_login",
    argNames: ["that", "username", "password"],
  );

  @override
  Future<Api> crateApiApiNew({required String databaseUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databaseUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiNewConstMeta,
        argValues: [databaseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiNewConstMeta =>
      const TaskConstMeta(debugName: "Api_new", argNames: ["databaseUrl"]);

  @override
  Future<Api> crateApiApiNewWithDb({required String databaseUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databaseUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiNewWithDbConstMeta,
        argValues: [databaseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiNewWithDbConstMeta => const TaskConstMeta(
    debugName: "Api_new_with_db",
    argNames: ["databaseUrl"],
  );

  @override
  Future<User> crateApiApiRegister({
    required Api that,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiRegisterConstMeta,
        argValues: [that, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiRegisterConstMeta => const TaskConstMeta(
    debugName: "Api_register",
    argNames: ["that", "username", "password"],
  );

  @override
  Future<ChatMessage> crateApiApiSendMessage({
    required Api that,
    required String roomId,
    required String userId,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_String(userId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiSendMessageConstMeta,
        argValues: [that, roomId, userId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSendMessageConstMeta => const TaskConstMeta(
    debugName: "Api_send_message",
    argNames: ["that", "roomId", "userId", "message"],
  );

  @override
  Future<String> crateApiApiStartGame({
    required Api that,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiStartGameConstMeta,
        argValues: [that, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiStartGameConstMeta => const TaskConstMeta(
    debugName: "Api_start_game",
    argNames: ["that", "roomId"],
  );

  @override
  Future<String> crateApiApiSubmitAction({
    required Api that,
    required String actorId,
    required String actionType,
    String? targetId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(actorId, serializer);
          sse_encode_String(actionType, serializer);
          sse_encode_opt_String(targetId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiSubmitActionConstMeta,
        argValues: [that, actorId, actionType, targetId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSubmitActionConstMeta => const TaskConstMeta(
    debugName: "Api_submit_action",
    argNames: ["that", "actorId", "actionType", "targetId"],
  );

  @override
  Future<String> crateApiApiTestConnection({required Api that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiTestConnectionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiTestConnectionConstMeta =>
      const TaskConstMeta(debugName: "Api_test_connection", argNames: ["that"]);

  @override
  Future<String> crateApiApiTestDb({required Api that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiTestDbConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiTestDbConstMeta =>
      const TaskConstMeta(debugName: "Api_test_db", argNames: ["that"]);

  @override
  Future<void> crateApiApiUpdateUsername({
    required Api that,
    required String userId,
    required String newUsername,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(userId, serializer);
          sse_encode_String(newUsername, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiUpdateUsernameConstMeta,
        argValues: [that, userId, newUsername],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiUpdateUsernameConstMeta => const TaskConstMeta(
    debugName: "Api_update_username",
    argNames: ["that", "userId", "newUsername"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Api => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Api => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Api
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Api
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Api
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ChatMessage(
      messageId: dco_decode_String(arr[0]),
      roomId: dco_decode_String(arr[1]),
      senderId: dco_decode_String(arr[2]),
      senderName: dco_decode_String(arr[3]),
      message: dco_decode_String(arr[4]),
      phaseType: dco_decode_String(arr[5]),
      createdAt: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  User dco_decode_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return User(
      userId: dco_decode_String(arr[0]),
      username: dco_decode_String(arr[1]),
      passwordHash: dco_decode_String(arr[2]),
      createdAt: dco_decode_String(arr[3]),
      lastLogin: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Vote dco_decode_vote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Vote(
      voteId: dco_decode_String(arr[0]),
      roomId: dco_decode_String(arr[1]),
      phaseId: dco_decode_String(arr[2]),
      voterId: dco_decode_String(arr[3]),
      targetId: dco_decode_String(arr[4]),
      createdAt: dco_decode_String(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Api
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Api
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Api
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageId = sse_decode_String(deserializer);
    var var_roomId = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_phaseType = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return ChatMessage(
      messageId: var_messageId,
      roomId: var_roomId,
      senderId: var_senderId,
      senderName: var_senderName,
      message: var_message,
      phaseType: var_phaseType,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  User sse_decode_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_passwordHash = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_lastLogin = sse_decode_opt_String(deserializer);
    return User(
      userId: var_userId,
      username: var_username,
      passwordHash: var_passwordHash,
      createdAt: var_createdAt,
      lastLogin: var_lastLogin,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Vote sse_decode_vote(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_voteId = sse_decode_String(deserializer);
    var var_roomId = sse_decode_String(deserializer);
    var var_phaseId = sse_decode_String(deserializer);
    var var_voterId = sse_decode_String(deserializer);
    var var_targetId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return Vote(
      voteId: var_voteId,
      roomId: var_roomId,
      phaseId: var_phaseId,
      voterId: var_voterId,
      targetId: var_targetId,
      createdAt: var_createdAt,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.messageId, serializer);
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.phaseType, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user(User self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.passwordHash, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_opt_String(self.lastLogin, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vote(Vote self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.voteId, serializer);
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.phaseId, serializer);
    sse_encode_String(self.voterId, serializer);
    sse_encode_String(self.targetId, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class ApiImpl extends RustOpaque implements Api {
  // Not to be used by end users
  ApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Api,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Api,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiPtr,
  );

  Future<Vote> castVote({
    required String roomId,
    required String voterId,
    required String targetId,
  }) => RustLib.instance.api.crateApiApiCastVote(
    that: this,
    roomId: roomId,
    voterId: voterId,
    targetId: targetId,
  );

  Future<String> createRoom({
    required String roomName,
    required int maxPlayers,
  }) => RustLib.instance.api.crateApiApiCreateRoom(
    that: this,
    roomName: roomName,
    maxPlayers: maxPlayers,
  );

  Future<String> forceNextPhase() =>
      RustLib.instance.api.crateApiApiForceNextPhase(that: this);

  Future<String> getGameState() =>
      RustLib.instance.api.crateApiApiGetGameState(that: this);

  Future<List<String>> getLocalIps() =>
      RustLib.instance.api.crateApiApiGetLocalIps(that: this);

  Future<String> joinRoom({required String hostIp}) =>
      RustLib.instance.api.crateApiApiJoinRoom(that: this, hostIp: hostIp);

  /// Stub: auth is handled by HTTP POST /auth/login
  Future<User> login({required String username, required String password}) =>
      RustLib.instance.api.crateApiApiLogin(
        that: this,
        username: username,
        password: password,
      );

  /// Stub: auth is handled by HTTP POST /auth/register
  Future<User> register({required String username, required String password}) =>
      RustLib.instance.api.crateApiApiRegister(
        that: this,
        username: username,
        password: password,
      );

  Future<ChatMessage> sendMessage({
    required String roomId,
    required String userId,
    required String message,
  }) => RustLib.instance.api.crateApiApiSendMessage(
    that: this,
    roomId: roomId,
    userId: userId,
    message: message,
  );

  /// Start the game engine for a specific room
  Future<String> startGame({required String roomId}) =>
      RustLib.instance.api.crateApiApiStartGame(that: this, roomId: roomId);

  Future<String> submitAction({
    required String actorId,
    required String actionType,
    String? targetId,
  }) => RustLib.instance.api.crateApiApiSubmitAction(
    that: this,
    actorId: actorId,
    actionType: actionType,
    targetId: targetId,
  );

  Future<String> testConnection() =>
      RustLib.instance.api.crateApiApiTestConnection(that: this);

  /// Stub: DB is server-side only
  Future<String> testDb() => RustLib.instance.api.crateApiApiTestDb(that: this);

  /// Stub: profile updates not yet implemented
  Future<void> updateUsername({
    required String userId,
    required String newUsername,
  }) => RustLib.instance.api.crateApiApiUpdateUsername(
    that: this,
    userId: userId,
    newUsername: newUsername,
  );
}
