// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class ChatMessage {
  final UuidValue messageId;
  final UuidValue gameId;
  final UuidValue? phaseId;
  final UuidValue? senderId;
  final String chatScope;
  final String messageText;
  final DateTime createdAt;

  const ChatMessage({
    required this.messageId,
    required this.gameId,
    this.phaseId,
    this.senderId,
    required this.chatScope,
    required this.messageText,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      gameId.hashCode ^
      phaseId.hashCode ^
      senderId.hashCode ^
      chatScope.hashCode ^
      messageText.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          gameId == other.gameId &&
          phaseId == other.phaseId &&
          senderId == other.senderId &&
          chatScope == other.chatScope &&
          messageText == other.messageText &&
          createdAt == other.createdAt;
}

class GameAction {
  final UuidValue actionId;
  final UuidValue gameId;
  final UuidValue phaseId;
  final UuidValue actorId;
  final UuidValue? targetId;
  final String actionType;
  final String? actionResult;
  final DateTime createdAt;

  const GameAction({
    required this.actionId,
    required this.gameId,
    required this.phaseId,
    required this.actorId,
    this.targetId,
    required this.actionType,
    this.actionResult,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      actionId.hashCode ^
      gameId.hashCode ^
      phaseId.hashCode ^
      actorId.hashCode ^
      targetId.hashCode ^
      actionType.hashCode ^
      actionResult.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameAction &&
          runtimeType == other.runtimeType &&
          actionId == other.actionId &&
          gameId == other.gameId &&
          phaseId == other.phaseId &&
          actorId == other.actorId &&
          targetId == other.targetId &&
          actionType == other.actionType &&
          actionResult == other.actionResult &&
          createdAt == other.createdAt;
}

class GameParticipant {
  final UuidValue gameParticipantId;
  final UuidValue gameId;
  final UuidValue playerId;
  final int roleId;
  final int? revealedRoleId;
  final bool isAlive;
  final int seatNumber;
  final DateTime joinedAt;
  final DateTime? diedAt;
  final String? deathReason;

  const GameParticipant({
    required this.gameParticipantId,
    required this.gameId,
    required this.playerId,
    required this.roleId,
    this.revealedRoleId,
    required this.isAlive,
    required this.seatNumber,
    required this.joinedAt,
    this.diedAt,
    this.deathReason,
  });

  @override
  int get hashCode =>
      gameParticipantId.hashCode ^
      gameId.hashCode ^
      playerId.hashCode ^
      roleId.hashCode ^
      revealedRoleId.hashCode ^
      isAlive.hashCode ^
      seatNumber.hashCode ^
      joinedAt.hashCode ^
      diedAt.hashCode ^
      deathReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameParticipant &&
          runtimeType == other.runtimeType &&
          gameParticipantId == other.gameParticipantId &&
          gameId == other.gameId &&
          playerId == other.playerId &&
          roleId == other.roleId &&
          revealedRoleId == other.revealedRoleId &&
          isAlive == other.isAlive &&
          seatNumber == other.seatNumber &&
          joinedAt == other.joinedAt &&
          diedAt == other.diedAt &&
          deathReason == other.deathReason;
}

enum GameStatus { waiting, starting, playing, finished, closed }

class Room {
  final UuidValue roomId;
  final UuidValue ownerId;
  final String roomName;
  final String roomType;
  final int maxPlayers;
  final GameStatus roomStatus;
  final DateTime? autoStartAt;
  final bool startedByOwner;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Room({
    required this.roomId,
    required this.ownerId,
    required this.roomName,
    required this.roomType,
    required this.maxPlayers,
    required this.roomStatus,
    this.autoStartAt,
    required this.startedByOwner,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      ownerId.hashCode ^
      roomName.hashCode ^
      roomType.hashCode ^
      maxPlayers.hashCode ^
      roomStatus.hashCode ^
      autoStartAt.hashCode ^
      startedByOwner.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Room &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          ownerId == other.ownerId &&
          roomName == other.roomName &&
          roomType == other.roomType &&
          maxPlayers == other.maxPlayers &&
          roomStatus == other.roomStatus &&
          autoStartAt == other.autoStartAt &&
          startedByOwner == other.startedByOwner &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class User {
  final UuidValue playerId;
  final String username;
  final String? email;
  final String passwordHash;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? lastLogin;

  const User({
    required this.playerId,
    required this.username,
    this.email,
    required this.passwordHash,
    required this.createdAt,
    required this.updatedAt,
    this.lastLogin,
  });

  @override
  int get hashCode =>
      playerId.hashCode ^
      username.hashCode ^
      email.hashCode ^
      passwordHash.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      lastLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          playerId == other.playerId &&
          username == other.username &&
          email == other.email &&
          passwordHash == other.passwordHash &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          lastLogin == other.lastLogin;
}
