// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ChatMessage {
  final String messageId;
  final String roomId;
  final String senderId;
  final String senderName;
  final String message;
  final String phaseType;
  final String createdAt;

  const ChatMessage({
    required this.messageId,
    required this.roomId,
    required this.senderId,
    required this.senderName,
    required this.message,
    required this.phaseType,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      roomId.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      message.hashCode ^
      phaseType.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          roomId == other.roomId &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          message == other.message &&
          phaseType == other.phaseType &&
          createdAt == other.createdAt;
}

class User {
  final String userId;
  final String username;
  final String passwordHash;
  final String createdAt;
  final String? lastLogin;

  const User({
    required this.userId,
    required this.username,
    required this.passwordHash,
    required this.createdAt,
    this.lastLogin,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      username.hashCode ^
      passwordHash.hashCode ^
      createdAt.hashCode ^
      lastLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          username == other.username &&
          passwordHash == other.passwordHash &&
          createdAt == other.createdAt &&
          lastLogin == other.lastLogin;
}

class Vote {
  final String voteId;
  final String roomId;
  final String phaseId;
  final String voterId;
  final String targetId;
  final String createdAt;

  const Vote({
    required this.voteId,
    required this.roomId,
    required this.phaseId,
    required this.voterId,
    required this.targetId,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      voteId.hashCode ^
      roomId.hashCode ^
      phaseId.hashCode ^
      voterId.hashCode ^
      targetId.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Vote &&
          runtimeType == other.runtimeType &&
          voteId == other.voteId &&
          roomId == other.roomId &&
          phaseId == other.phaseId &&
          voterId == other.voterId &&
          targetId == other.targetId &&
          createdAt == other.createdAt;
}
