services:
  backend:
    build: .
    container_name: areyoughost_backend
    environment:
      - ACTIVE_DB=SUPABASE
      - DATABASE_URL_SUPABASE=REMOVED_DB_URL
      - JWT_SECRET=REMOVED_JWT_SECRET
      - RUST_LOG=info
    ports:
      - "3000:3000"
      - "8888:8888"
      - "8889:8889/udp"
    restart: unless-stopped
