services:
  backend:
    build: .
    container_name: areyoughost_backend
    env_file:
      - .env
    environment:
      - ACTIVE_DB=SUPABASE
      - RUST_LOG=info
    ports:
      - "3000:3000"
      - "8888:8888"
      - "8889:8889/udp"
    restart: unless-stopped
