BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================
-- UPDATED_AT TRIGGER
-- =========================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================
-- PLAYERS
-- =========================
CREATE TABLE IF NOT EXISTS players (
  player_id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username      text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  last_login    timestamptz,
  CONSTRAINT username_len CHECK (length(username) BETWEEN 3 AND 20)
);

DROP TRIGGER IF EXISTS trg_players_updated_at ON players;
CREATE TRIGGER trg_players_updated_at
BEFORE UPDATE ON players
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================
-- ROOMS
-- =========================
CREATE TABLE IF NOT EXISTS rooms (
  room_id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id      uuid NOT NULL,
  room_name     text NOT NULL,
  max_players   int NOT NULL DEFAULT 16 CHECK (max_players BETWEEN 1 AND 16),
  is_public     boolean NOT NULL DEFAULT true,
  room_status   text NOT NULL CHECK (room_status IN ('WAITING','PLAYING','CLOSED')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (owner_id) REFERENCES players(player_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS trg_rooms_updated_at ON rooms;
CREATE TRIGGER trg_rooms_updated_at
BEFORE UPDATE ON rooms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================
-- ROOM MEMBERS
-- =========================
CREATE TABLE IF NOT EXISTS room_members (
  room_member_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id        uuid NOT NULL,
  player_id      uuid NOT NULL,
  member_status  text NOT NULL CHECK (member_status IN ('JOINED','LEFT')),
  joined_at      timestamptz DEFAULT now(),
  FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE,
  FOREIGN KEY (player_id) REFERENCES players(player_id) ON DELETE CASCADE,
  UNIQUE (room_id, player_id)
);

-- =========================
-- ROLES (IMPROVED)
-- =========================
-- =========================
-- ROLES
-- =========================
CREATE TABLE IF NOT EXISTS public.roles (
  role_id integer generated by default as identity not null,
  role_code text not null,
  role_name text not null,
  faction text not null,
  description text null,
  seer_result text not null,
  aura_result text not null,
  min_players integer not null default 1,
  max_players integer not null default 16,
  is_unique boolean not null default true,
  is_enabled boolean not null default true,
  role_priority integer not null default 0,
  constraint roles_pkey primary key (role_id),
  constraint roles_role_code_key unique (role_code),
  constraint roles_role_name_key unique (role_name),
  constraint roles_min_players_check check ((min_players >= 1)),
  constraint roles_aura_result_check check (aura_result = any (array['GOOD'::text, 'EVIL'::text])),
  constraint roles_seer_result_check check (seer_result = any (array['VILLAGER'::text, 'GHOST'::text])),
  constraint roles_faction_check check (faction = any (array['VILLAGER'::text, 'GHOST'::text, 'SPECIAL'::text])),
  constraint roles_max_players_check check ((max_players <= 16))
);

CREATE INDEX IF NOT EXISTS ix_roles_faction on public.roles using btree (faction);
CREATE INDEX IF NOT EXISTS ix_roles_player_range on public.roles using btree (min_players, max_players);

-- =========================
-- SKILLS
-- =========================
CREATE TABLE IF NOT EXISTS skills (
  skill_id     serial PRIMARY KEY,
  skill_code   text UNIQUE NOT NULL,
  skill_name   text NOT NULL,
  skill_type   text NOT NULL, -- KILL / PROTECT / CHECK / PASSIVE / SPECIAL
  phase        text NOT NULL CHECK (phase IN ('DAY','NIGHT','ANY')),
  max_uses     int, -- NULL = unlimited
  description  text
);

-- =========================
-- ROLE_SKILLS (MANY-TO-MANY)
-- =========================
CREATE TABLE IF NOT EXISTS role_skills (
  id        serial PRIMARY KEY,
  role_id   int NOT NULL,
  skill_id  int NOT NULL,
  FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE,
  FOREIGN KEY (skill_id) REFERENCES skills(skill_id) ON DELETE CASCADE,
  UNIQUE(role_id, skill_id)
);

-- =========================
-- GAMES
-- =========================
CREATE TABLE IF NOT EXISTS games (
  game_id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id        uuid NOT NULL,
  game_status    text NOT NULL CHECK (game_status IN ('WAITING','ONGOING','FINISHED')),
  random_seed    bigint NOT NULL,
  started_at     timestamptz,
  ended_at       timestamptz,
  winner_faction text,
  FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE
);

-- =========================
-- GAME PARTICIPANTS
-- =========================
CREATE TABLE IF NOT EXISTS game_participants (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id      uuid NOT NULL,
  player_id    uuid NOT NULL,
  role_id      int,
  is_alive     boolean DEFAULT true,
  seat_number  int,
  joined_at    timestamptz DEFAULT now(),
  died_at      timestamptz,
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE,
  FOREIGN KEY (player_id) REFERENCES players(player_id),
  FOREIGN KEY (role_id) REFERENCES roles(role_id),
  UNIQUE(game_id, player_id)
);

-- =========================
-- GAME PHASES
-- =========================
CREATE TABLE IF NOT EXISTS game_phases (
  phase_id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id      uuid NOT NULL,
  phase_type   text CHECK (phase_type IN ('DAY','NIGHT')),
  phase_order  int,
  started_at   timestamptz DEFAULT now(),
  ended_at     timestamptz,
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

-- =========================
-- GAME ACTIONS
-- =========================
CREATE TABLE IF NOT EXISTS game_actions (
  action_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id     uuid NOT NULL,
  phase_id    uuid,
  actor_id    uuid,
  target_id   uuid,
  action_type text,
  payload     jsonb,
  created_at  timestamptz DEFAULT now(),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

-- =========================
-- VOTES
-- =========================
CREATE TABLE IF NOT EXISTS votes (
  vote_id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id      uuid,
  phase_id     uuid,
  voter_id     uuid,
  candidate_id uuid,
  created_at   timestamptz DEFAULT now()
);

-- =========================
-- CHAT
-- =========================
CREATE TABLE IF NOT EXISTS chat_messages (
  message_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id      uuid,
  sender_id    uuid,
  chat_scope   text CHECK (chat_scope IN ('PUBLIC','GHOST')),
  message_text text,
  created_at   timestamptz DEFAULT now()
);

COMMIT;