BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==========================================
-- 1. ROLES & SKILLS (Metdata)
-- ==========================================

-- Roles Table
CREATE TABLE IF NOT EXISTS public.roles (
  role_id integer generated by default as identity not null,
  role_code text not null,
  role_name text not null,
  faction text not null,
  description text null,
  seer_result text not null,
  aura_result text not null,
  min_players integer not null default 1,
  max_players integer not null default 16,
  is_unique boolean not null default true,
  is_enabled boolean not null default true,
  role_priority integer not null default 0,
  role_img text null,
  constraint roles_pkey primary key (role_id),
  constraint roles_role_code_key unique (role_code)
);

-- Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
  skill_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  skill_code text not null unique,
  skill_name text not null,
  description text null,
  phase_type text not null,
  target_type text not null,
  usage_limit integer null,
  can_skip boolean not null default true,
  is_enabled boolean not null default true,
  skill_img text null
);

-- Role-Skills Mapping Table
CREATE TABLE IF NOT EXISTS public.role_skills (
  role_skill_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  role_id integer REFERENCES roles(role_id) ON DELETE CASCADE,
  skill_id uuid REFERENCES skills(skill_id) ON DELETE CASCADE,
  skill_order integer not null default 0,
  usage_limit_override integer null
);

-- ==========================================
-- 2. PLAYERS & SESSIONS
-- ==========================================

-- Players Table
CREATE TABLE IF NOT EXISTS public.players (
  player_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username text not null UNIQUE,
  email text null,
  password_hash text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  last_login timestamp with time zone
);

-- Player Sessions Table
CREATE TABLE IF NOT EXISTS public.player_sessions (
  session_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id uuid REFERENCES players(player_id) ON DELETE CASCADE,
  refresh_token_hash text null,
  created_at timestamp with time zone not null default now(),
  expires_at timestamp with time zone not null,
  revoked_at timestamp with time zone
);

-- Friendships Table
CREATE TABLE IF NOT EXISTS public.friendships (
  friendship_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id uuid REFERENCES players(player_id),
  addressee_id uuid REFERENCES players(player_id),
  status text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- ==========================================
-- 3. ROOMS & LOBBY
-- ==========================================

-- Rooms Table
CREATE TABLE IF NOT EXISTS public.rooms (
  room_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid REFERENCES players(player_id),
  room_name text not null,
  room_type text not null,
  max_players integer not null default 16,
  room_status text not null,
  auto_start_at timestamp with time zone,
  started_by_owner boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Room Members Table
CREATE TABLE IF NOT EXISTS public.room_members (
  room_member_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid REFERENCES rooms(room_id) ON DELETE CASCADE,
  player_id uuid REFERENCES players(player_id) ON DELETE CASCADE,
  member_status text not null,
  joined_at timestamp with time zone not null default now(),
  left_at timestamp with time zone,
  lost_at timestamp with time zone
);

-- Room Invites Table
CREATE TABLE IF NOT EXISTS public.room_invites (
  invite_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid REFERENCES rooms(room_id) ON DELETE CASCADE,
  inviter_id uuid REFERENCES players(player_id),
  invitee_id uuid REFERENCES players(player_id),
  status text not null,
  created_at timestamp with time zone not null default now(),
  responded_at timestamp with time zone
);

-- ==========================================
-- 4. GAMES & STATE
-- ==========================================

-- Games Table
CREATE TABLE IF NOT EXISTS public.games (
  game_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid REFERENCES rooms(room_id) ON DELETE CASCADE,
  room_type text not null,
  player_count integer not null,
  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone,
  game_status text not null,
  winner_faction text null,
  random_seed bigint not null,
  setup_json jsonb
);

-- Game Participants Table
CREATE TABLE IF NOT EXISTS public.game_participants (
  game_participant_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  player_id uuid REFERENCES players(player_id),
  role_id integer REFERENCES roles(role_id),
  revealed_role_id integer REFERENCES roles(role_id),
  is_alive boolean not null default true,
  seat_number integer not null,
  joined_at timestamp with time zone not null default now(),
  died_at timestamp with time zone,
  death_reason text
);

-- Participant States Table
CREATE TABLE IF NOT EXISTS public.participant_states (
  participant_state_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_participant_id uuid REFERENCES game_participants(game_participant_id) ON DELETE CASCADE,
  original_role_id integer not null,
  current_role_id integer not null,
  original_faction text not null,
  current_faction text not null,
  is_silenced boolean not null default false,
  silenced_until_phase_id uuid,
  hidden_target_participant_id uuid,
  last_protected_target_id uuid,
  doctor_power_consumed boolean not null default false,
  lucky_one_turned boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Participant Skill Usages Table
CREATE TABLE IF NOT EXISTS public.participant_skill_usages (
  participant_skill_usage_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_participant_id uuid REFERENCES game_participants(game_participant_id) ON DELETE CASCADE,
  skill_id uuid REFERENCES skills(skill_id),
  used_count integer not null default 0,
  remaining_uses integer,
  updated_at timestamp with time zone not null default now()
);

-- ==========================================
-- 5. GAMEFLOW & ACTIONS
-- ==========================================

-- Game Phases Table
CREATE TABLE IF NOT EXISTS public.game_phases (
  phase_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  phase_type text not null,
  vote_scope text,
  phase_order integer not null,
  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone
);

-- Game Actions Table
CREATE TABLE IF NOT EXISTS public.game_actions (
  action_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  phase_id uuid REFERENCES game_phases(phase_id),
  actor_id uuid REFERENCES game_participants(game_participant_id),
  target_id uuid,
  action_type text not null,
  action_payload jsonb,
  created_at timestamp with time zone not null default now()
);

-- Action Resolutions Table
CREATE TABLE IF NOT EXISTS public.action_resolutions (
  resolution_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  action_id uuid REFERENCES game_actions(action_id) ON DELETE CASCADE,
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  phase_id uuid REFERENCES game_phases(phase_id),
  outcome_type text not null,
  outcome_payload jsonb,
  created_at timestamp with time zone not null default now()
);

-- Phase Outcomes Table
CREATE TABLE IF NOT EXISTS public.phase_outcomes (
  phase_outcome_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  phase_id uuid REFERENCES game_phases(phase_id),
  game_participant_id uuid REFERENCES game_participants(game_participant_id),
  outcome_type text not null,
  source_participant_id uuid,
  related_action_id uuid,
  metadata jsonb,
  created_at timestamp with time zone not null default now()
);

-- Votes Table
CREATE TABLE IF NOT EXISTS public.votes (
  vote_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  phase_id uuid REFERENCES game_phases(phase_id),
  voter_id uuid REFERENCES game_participants(game_participant_id),
  candidate_id uuid,
  created_at timestamp with time zone not null default now()
);

-- ==========================================
-- 6. ANALYTICS & LOGS
-- ==========================================

-- Game Results Table
CREATE TABLE IF NOT EXISTS public.game_results (
  result_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  winner_faction text not null,
  duration_seconds integer not null,
  total_turns integer not null,
  created_at timestamp with time zone not null default now()
);

-- Chat Messages Table
CREATE TABLE IF NOT EXISTS public.chat_messages (
  message_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  phase_id uuid,
  sender_id uuid,
  chat_scope text not null,
  message_text text not null,
  created_at timestamp with time zone not null default now()
);

-- Network Logs Table
CREATE TABLE IF NOT EXISTS public.network_logs (
  log_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id uuid REFERENCES games(game_id) ON DELETE CASCADE,
  session_id uuid,
  direction text not null,
  msg_type text not null,
  bytes integer not null,
  dropped integer not null default 0,
  latency_ms integer,
  created_at timestamp with time zone not null default now()
);

COMMIT;