// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'roles.dart';

class ParticipantInfo {
  final GameParticipant model;
  final String username;
  final Role? role;
  final bool isSilenced;
  final UuidValue? protectedBy;
  final UuidValue? hiddenTarget;

  const ParticipantInfo({
    required this.model,
    required this.username,
    this.role,
    required this.isSilenced,
    this.protectedBy,
    this.hiddenTarget,
  });

  @override
  int get hashCode =>
      model.hashCode ^
      username.hashCode ^
      role.hashCode ^
      isSilenced.hashCode ^
      protectedBy.hashCode ^
      hiddenTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParticipantInfo &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          username == other.username &&
          role == other.role &&
          isSilenced == other.isSilenced &&
          protectedBy == other.protectedBy &&
          hiddenTarget == other.hiddenTarget;
}
