/// build.rs — Generate RoleType enum at compile-time from role definitions.
/// In a real scenario, you'd read from a JSON/TOML file exported from DB.
/// This keeps the enum always in sync with your 16 official roles.

use std::env;
use std::fs;

fn main() {
    // Official 16 roles: (CODE, PascalName)
    let roles: &[(&str, &str)] = &[
        // Villager faction (V1–V9)
        ("VILLAGER",      "Villager"),
        ("SEER",          "Seer"),
        ("DOCTOR",        "Doctor"),
        ("SOLDIER",       "Soldier"),
        ("POLICE",        "Police"),
        ("MONK",          "Monk"),
        ("MEDIUM",        "Medium"),
        ("UNDERTAKER",    "Undertaker"),
        ("FOOL",          "Fool"),
        // Ghost faction (G10–G14)
        ("GHOST",         "Ghost"),
        ("QUEENGHOST",    "QueenGhost"),
        ("AVENGERGHOST",  "AvengerGhost"),
        ("DECEIVERGHOST", "DeceiverGhost"),
        ("DARKSHAMAN",    "DarkShaman"),
        // Special faction (S15–S16)
        ("SERIALKILLER",  "SerialKiller"),
        ("NEMESIS",       "Nemesis"),
    ];

    // ── Generate role_type.rs ─────────────────────────────────────
    let mut code = String::from(
        "/// AUTO-GENERATED by build.rs — DO NOT EDIT MANUALLY\n\
         use serde::{Deserialize, Serialize};\n\n\
         #[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]\n\
         #[repr(u8)]\n\
         pub enum RoleType {\n"
    );

    for (_, pascal) in roles {
        code.push_str(&format!("    {},\n", pascal));
    }
    code.push_str("}\n\n");

    // from_code
    code.push_str(
        "impl RoleType {\n\
             pub fn from_code(code: &str) -> Self {\n\
                 match code.to_uppercase().as_str() {\n",
    );
    for (role_code, pascal) in roles {
        code.push_str(&format!(
            "                \"{}\" => RoleType::{},\n",
            role_code, pascal
        ));
    }
    code.push_str(
        "                _ => RoleType::Villager, // default fallback\n\
                 }\n\
             }\n\n",
    );

    // to_code
    code.push_str(
        "    pub fn to_code(&self) -> &'static str {\n\
                 match self {\n",
    );
    for (role_code, pascal) in roles {
        code.push_str(&format!(
            "                RoleType::{} => \"{}\",\n",
            pascal, role_code
        ));
    }
    code.push_str(
        "            }\n\
             }\n\
         }\n",
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(format!("{}/role_type.rs", out_dir), code).unwrap();

    // Re-run if this file changes
    println!("cargo:rerun-if-changed=build.rs");
}
