// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class CastVoteRequest {
  final UuidValue roomId;
  final UuidValue targetId;

  const CastVoteRequest({required this.roomId, required this.targetId});

  @override
  int get hashCode => roomId.hashCode ^ targetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CastVoteRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          targetId == other.targetId;
}

class NightActionRequest {
  final UuidValue roomId;
  final String actionType;
  final UuidValue? targetId;

  const NightActionRequest({
    required this.roomId,
    required this.actionType,
    this.targetId,
  });

  @override
  int get hashCode => roomId.hashCode ^ actionType.hashCode ^ targetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NightActionRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          actionType == other.actionType &&
          targetId == other.targetId;
}

class StartGameRequest {
  final UuidValue roomId;

  const StartGameRequest({required this.roomId});

  @override
  int get hashCode => roomId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartGameRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId;
}
