// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../game_logic/phase_machine.dart';
import '../game_logic/roles.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class CastVoteRequest {
  final UuidValue roomId;
  final UuidValue targetId;

  const CastVoteRequest({required this.roomId, required this.targetId});

  @override
  int get hashCode => roomId.hashCode ^ targetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CastVoteRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          targetId == other.targetId;
}

class ChatEntry {
  final String senderUsername;
  final String messageText;
  final BigInt timestamp;

  const ChatEntry({
    required this.senderUsername,
    required this.messageText,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      senderUsername.hashCode ^ messageText.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatEntry &&
          runtimeType == other.runtimeType &&
          senderUsername == other.senderUsername &&
          messageText == other.messageText &&
          timestamp == other.timestamp;
}

class ChatMessageRequest {
  final UuidValue roomId;
  final String messageText;

  const ChatMessageRequest({required this.roomId, required this.messageText});

  @override
  int get hashCode => roomId.hashCode ^ messageText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          messageText == other.messageText;
}

class DeathInfo {
  final UuidValue playerId;
  final String username;
  final String roleName;

  const DeathInfo({
    required this.playerId,
    required this.username,
    required this.roleName,
  });

  @override
  int get hashCode => playerId.hashCode ^ username.hashCode ^ roleName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeathInfo &&
          runtimeType == other.runtimeType &&
          playerId == other.playerId &&
          username == other.username &&
          roleName == other.roleName;
}

class GameEvent {
  final GameEventType eventType;
  final List<DeathInfo> deaths;
  final String? winnerFaction;
  final Value? extra;

  const GameEvent({
    required this.eventType,
    required this.deaths,
    this.winnerFaction,
    this.extra,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      deaths.hashCode ^
      winnerFaction.hashCode ^
      extra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameEvent &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          deaths == other.deaths &&
          winnerFaction == other.winnerFaction &&
          extra == other.extra;
}

enum GameEventType {
  nightResolution,
  voteResult,
  gameOver,
  avengerVengeance,
  nemesisWin,
  foolWin,
}

class GamePhaseChange {
  final PhaseType phase;
  final int dayNumber;
  final int durationSecs;
  final BigInt serverTimestamp;
  final List<ChatEntry>? nightChatHistory;

  const GamePhaseChange({
    required this.phase,
    required this.dayNumber,
    required this.durationSecs,
    required this.serverTimestamp,
    this.nightChatHistory,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      dayNumber.hashCode ^
      durationSecs.hashCode ^
      serverTimestamp.hashCode ^
      nightChatHistory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamePhaseChange &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          dayNumber == other.dayNumber &&
          durationSecs == other.durationSecs &&
          serverTimestamp == other.serverTimestamp &&
          nightChatHistory == other.nightChatHistory;
}

class LeaveRoomRequest {
  final UuidValue roomId;

  const LeaveRoomRequest({required this.roomId});

  @override
  int get hashCode => roomId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LeaveRoomRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId;
}

class NightActionRequest {
  final UuidValue roomId;
  final SkillType actionType;
  final UuidValue? targetId;

  const NightActionRequest({
    required this.roomId,
    required this.actionType,
    this.targetId,
  });

  @override
  int get hashCode => roomId.hashCode ^ actionType.hashCode ^ targetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NightActionRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          actionType == other.actionType &&
          targetId == other.targetId;
}

class ParticipantInfoDto {
  final UuidValue playerId;
  final String username;
  final bool isAlive;
  final int seatNumber;
  final bool isOnline;

  const ParticipantInfoDto({
    required this.playerId,
    required this.username,
    required this.isAlive,
    required this.seatNumber,
    required this.isOnline,
  });

  @override
  int get hashCode =>
      playerId.hashCode ^
      username.hashCode ^
      isAlive.hashCode ^
      seatNumber.hashCode ^
      isOnline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParticipantInfoDto &&
          runtimeType == other.runtimeType &&
          playerId == other.playerId &&
          username == other.username &&
          isAlive == other.isAlive &&
          seatNumber == other.seatNumber &&
          isOnline == other.isOnline;
}

class RoomStateSync {
  final UuidValue roomId;
  final List<ParticipantInfoDto> participants;
  final int aliveCount;

  const RoomStateSync({
    required this.roomId,
    required this.participants,
    required this.aliveCount,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^ participants.hashCode ^ aliveCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomStateSync &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          participants == other.participants &&
          aliveCount == other.aliveCount;
}

class ServerResponse {
  final bool success;
  final String? error;

  const ServerResponse({required this.success, this.error});

  @override
  int get hashCode => success.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerResponse &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error;
}

class StartGameRequest {
  final UuidValue roomId;

  const StartGameRequest({required this.roomId});

  @override
  int get hashCode => roomId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartGameRequest &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId;
}
